version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch-container
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - D:/docker-volume/elasticsearch-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
  kibana:
    image: kibana:8.7.1
    container_name: kibana-container
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200   
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk    
      
volumes:
  elasticsearch-volume:

networks:
  elk: